// LOGIN , ACCOUNT MGMT,
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR'
export const SET_AUTHORIZED = 'SET_AUTHORIZED'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const GET_SIGNED_IN_USER = 'GET_SIGNED_IN_USER'
export const SET_AUTHENTICATED_USER = 'SET_AUTHENTICATED_USER'

export const FETCH_JSON_HELLO = 'FETCH_JSON_HELLO'
export const SET_ERROR = 'SET_ERROR'
export const SET_MESSAGE = 'SET_MESSAGE'
