// LOGIN , ACCOUNT MGMT,
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR'
export const SET_AUTHORIZED = 'SET_AUTHORIZED'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const GET_SIGNED_IN_USER = 'GET_SIGNED_IN_USER'
export const SET_AUTHENTICATED_USER = 'SET_AUTHENTICATED_USER'

export const FETCH_JSON_HELLO = 'FETCH_JSON_HELLO'
export const SET_ERROR = 'SET_ERROR'
export const SET_MESSAGE = 'SET_MESSAGE'

export const GET_EXAMPLE = 'GET_EXAMPLE'
export const PUT_EXAMPLE = 'PUT_EXAMPLE'
export const POST_EXAMPLE = 'POST_EXAMPLE'
export const ERROR_EXAMPLE = 'ERROR_EXAMPLE'

export const SAVE_CONFIGURATION = 'SAVE_CONFIGURATION'

export const FETCH_GRAPH_DATA = 'FETCH_GRAPH_DATA'
export const SET_GRAPH_DATA = 'SET_GRAPH_DATA'

export const FETCH_SIGNAL_DATA = 'FETCH_SIGNAL_DATA'
export const SET_SIGNAL_DATA = 'SET_SIGNAL_DATA'